### ISSUE TITLE
Upload folder

### ISSUE THREAD

**Issue by MattCowgill** [deka0106/upload-to-dropbox#2]
Hi,
Thank you so much for this action, it's really useful. 
I'd like to use it to upload a folder and all its contents, rather than an individual file. Is this possible?
Thanks
Matt

**Comment by deka0106** [comment]
Thank you for your suggestion.

Because my use case is to upload a single file with specified name, I didn't consider uploading a folder.
e.g. https://github.com/deka0106/latex-container/blob/dropbox-diff/.github/workflows/upload.yml#L34

But there are three possible scenarios, which I will try to support someday.
- file: 1 file, path: 1 file
    - e.g. `./dist/out.pdf` -> `/thesis/my_thesis.pdf`
- file: 1 file, path: folder
    - e.g. `./dist/out.pdf` -> `/thesis/`
- file: n files, path: folder
    - e.g. `./dist/*` -> `/dist/`

Sorry for too late reply.

**Comment by deka0106** [comment]
Uploading multiple files by glob is available in v2.
